# Load train and test data

In [41]:
import cv2

def load_image(image_path, dimension=(224, 224)):
    win_size = dimension
    cell_size = (8, 8)
    block_size = (16, 16)
    block_stride = (8, 8)
    num_bins = 9

    hog = cv2.HOGDescriptor(win_size, block_size, block_stride, cell_size, num_bins)
    
    image = cv2.imread(image_path, cv2.IMREAD_COLOR)
    image = cv2.resize(image, dimension)
    image_gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    print(image_gray)
    hog_descriptor = hog.compute(image_gray)
    return hog_descriptor

In [42]:

img = load_image("groceries/BEANS/BEANS0000.png", (224, 224))
print(img.shape)
print(img)

[[128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 ...
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]
 [128 128 128 ... 128 128 128]]
(26244,)
[0. 0. 0. ... 0. 0. 0.]


In [43]:

img = load_image("cifar-10/airplane/0.jpg", (64, 64))
print(img.shape)
print(img)

[[184 184 183 ... 177 175 174]
 [184 183 183 ... 178 176 175]
 [183 183 182 ... 181 177 176]
 ...
 [191 191 190 ... 181 180 179]
 [192 191 191 ... 181 180 180]
 [192 192 191 ... 181 180 180]]
(1764,)
[0.19105908 0.04895691 0.1470907  ... 0.08615888 0.14349894 0.13855472]


In [50]:
import cv2
import numpy as np
import onnxruntime as rt

def load_image_2(image_path, feature_extractor_path, dimension=(224, 224)):
    image = cv2.imread(image_path, cv2.IMREAD_COLOR)
    image = cv2.resize(image, dimension)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = image - [103.939, 116.779, 123.68]

    session = rt.InferenceSession(feature_extractor_path, providers=["CPUExecutionProvider"])
    input_name = session.get_inputs()[0].name

    test_sample_bulk = np.array([image.astype(np.float64)])
    onx_features = session.run(None, {input_name: test_sample_bulk})[0][0]

    return onx_features


img = load_image_2("groceries/BEANS/BEANS0000.png", "resnet50_feature_extractor_groceries_224_224_3.onnx", (224, 224))
print(img.shape)
print(img)

img = load_image_2("cifar-10/airplane/0.jpg", "resnet50_feature_extractor_cifar10_64_64_3.onnx", (64, 64))
print(img.shape)
print(img)

(2048,)
[0.12455437 0.3046711  0.01450814 ... 0.03151937 0.7242586  0.3015578 ]
(2048,)
[0.02925953 0.7805724  2.7778416  ... 1.8154366  0.         0.33503237]
